Import all the csv files from MachineLearningCVE folder

In [ ]:
import os
from pathlib import Path
import pandas as pd
import numpy as np
from pprint import pprint

ROOT = Path('.')
DATA_DIR = ROOT / '../../MachineLearningCVE'
OUTPUT_DIR = ROOT / '../../MachineLearningCVE_Cleaned'
OUTPUT_DIR.mkdir(exist_ok=True)

print(ROOT)
print(DATA_DIR)
print(OUTPUT_DIR)

In [18]:
# Import libraries and set up paths
import os
from pathlib import Path
import pandas as pd
import numpy as np
from pprint import pprint

ROOT = Path('.')
DATA_DIR = ROOT / '../../MachineLearningCVE'
OUTPUT_DIR = ROOT / '../../MachineLearningCVE_Cleaned'
OUTPUT_DIR.mkdir(exist_ok=True)

# discover CSV files
csv_files = sorted([p for p in DATA_DIR.iterdir() if p.suffix.lower() == '.csv'])
print(f'Found {len(csv_files)} CSV files in', DATA_DIR)
pprint([p.name for p in csv_files])

# load into DataFrames dictionary (do not modify originals on disk)
raw_dfs = {}
for p in csv_files:
    try:
        df = pd.read_csv(p)
    except Exception as e:
        print(f'Failed to read {p.name}:', e)
        continue
    raw_dfs[p.name] = df

# show initial shapes and headers
for name, df in raw_dfs.items():
    print(f'-- {name} : shape={df.shape}')
    print('  columns=', list(df.columns)[:10])

Found 8 CSV files in ..\..\MachineLearningCVE
['Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
 'Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
 'Friday-WorkingHours-Morning.pcap_ISCX.csv',
 'Monday-WorkingHours.pcap_ISCX.csv',
 'Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
 'Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
 'Tuesday-WorkingHours.pcap_ISCX.csv',
 'Wednesday-workingHours.pcap_ISCX.csv']
-- Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv : shape=(225745, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv : shape=(286467, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Friday-WorkingHours-Morning.pcap_ISCX.csv : shape=(191033, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Monday-WorkingHours.pcap_ISCX.csv : shape=(529918, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv : shape=(288602, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv : shape=(170366, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Tuesday-WorkingHours.pcap_ISCX.csv : shape=(445909, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']
-- Wednesday-workingHours.pcap_ISCX.csv : shape=(692703, 79)
  columns= [' Destination Port', ' Flow Duration', ' Total Fwd Packets', ' Total Backward Packets', 'Total Length of Fwd Packets', ' Total Length of Bwd Packets', ' Fwd Packet Length Max', ' Fwd Packet Length Min', ' Fwd Packet Length Mean', ' Fwd Packet Length Std']

### Do one operation in each cell:

After every step of cleaning:
- Show how many Values are there
- Print those values

Saving the cleaned files:
- Write a script to save all the cleaned files in a folder called "MachineLearningCVE_Cleaned"
- All the cleaned CSV files must be saved in that folder

After saving the final file 
- Print the shape from old csv and new csv of each file
- header of each files
- Come up with something

## NOTE: Do note change anything from the original CSV files

In [22]:
# Remove duplicate network records or repeated entries
# 1) Remove duplicate rows (exact duplicates)
cleaned_dfs = {}  # will hold cleaned DataFrames
duplicates_info = {}
for name, df in raw_dfs.items():
    before = len(df)
    # keep first occurrence, drop exact duplicate rows
    deduped = df.drop_duplicates(keep='first').reset_index(drop=True)
    after = len(deduped)
    duplicates_info[name] = {'before': before, 'after': after, 'removed': before - after}
    cleaned_dfs[name] = deduped

# print summary and show sample duplicates for each file (if any)
for name, info in duplicates_info.items():
    print(f"{name}: rows before={info['before']}, after={info['after']}, removed={info['removed']}")
    if info['removed'] > 0:
        print(' Sample duplicate rows (first 3 after dedup detection):')
        # show rows that were duplicates by comparing with original index
        df_orig = raw_dfs[name]
        # find duplicates boolean mask
        dup_mask = df_orig.duplicated(keep='first')
        display(df_orig[dup_mask].head(3))

# Keep cleaned_dfs for further steps
len(cleaned_dfs)

Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv: rows before=225745, after=223112, removed=2633
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
2109,80,77,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2257,443,3,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
2749,443,49,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv: rows before=286467, after=214114, removed=72353
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
93,53,201,2,2,88,188,44,44,44.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
98,53,201,2,2,88,188,44,44,44.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
100,53,161,2,2,64,158,32,32,32.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Friday-WorkingHours-Morning.pcap_ISCX.csv: rows before=191033, after=184145, removed=6888
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
285,443,3,2,0,91,0,85,6,45.5,55.861436,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
334,8612,17,11,0,198,0,18,18,18.0,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
335,8612,17,11,0,198,0,18,18,18.0,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Monday-WorkingHours.pcap_ISCX.csv: rows before=529918, after=502983, removed=26935
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
2,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
3,49188,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
6,49486,1,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv: rows before=288602, after=252972, removed=35630
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
277,53,142,2,2,70,102,35,35,35.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
824,80,78,2,0,12,0,6,6,6.0,0.0,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
1251,80,143,2,0,0,0,0,0,0.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv: rows before=170366, after=164300, removed=6066
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
53,53,210,2,2,64,96,32,32,32.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
54,53,162,2,2,64,158,32,32,32.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
63,53,214,2,2,64,96,32,32,32.0,0.0,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Tuesday-WorkingHours.pcap_ISCX.csv: rows before=445909, after=421844, removed=24065
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
172,389,0,2,0,7,0,7,0,3.5,4.949747,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
178,389,1,2,0,7,0,7,0,3.5,4.949747,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
227,389,1,2,0,39,0,39,0,19.5,27.577164,...,32,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

Wednesday-workingHours.pcap_ISCX.csv: rows before=692703, after=610794, removed=81909
 Sample duplicate rows (first 3 after dedup detection):

,Destination Port,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,Fwd Packet Length Min,Fwd Packet Length Mean,Fwd Packet Length Std,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
91,443,3,2,0,91,0,85,6,45.5,55.861436,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
687,80,4,2,0,12,0,6,6,6.0,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN
690,80,4,2,0,12,0,6,6,6.0,0.000000,...,20,0.0,0.0,0,0,0.0,0.0,0,0,BENIGN

8

In [23]:
# 2) Handle missing or corrupted values
from ipaddress import ip_address

def is_valid_ip(x):
    if pd.isna(x):
        return False
    try:
        ip_address(str(x))
        return True
    except Exception:
        return False

for name, df in list(cleaned_dfs.items()):
    print(f'Processing missing values for {name} - initial shape {df.shape}')
    missing_counts = df.isna().sum()
    print('  columns with missing values (top 10):')
    print(missing_counts[missing_counts>0].sort_values(ascending=False).head(10))

    # conservative rules: drop rows missing essential network fields if present
    essential_cols = []
    for c in ['Source IP','Destination IP','Source Port','Destination Port','Timestamp','timestamp','ts']:
        if c in df.columns:
            essential_cols.append(c)
    if essential_cols:
        before = len(df)
        df = df.dropna(subset=essential_cols).reset_index(drop=True)
        after = len(df)
        print(f'  dropped {before-after} rows missing essential columns: {essential_cols}')

    # attempt light normalization for IP columns: mark invalid IPs as NaN
    for col in df.columns:
        if 'ip' in col.lower() or 'addr' in col.lower():
            # vectorized validation might be slow; do small sample then fallback to apply
            df[col] = df[col].where(df[col].apply(is_valid_ip), other=np.nan)

    cleaned_dfs[name] = df

# end missing handling

Processing missing values for Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv - initial shape (223112, 79)
  columns with missing values (top 10):
Flow Bytes/s    4
dtype: int64
Processing missing values for Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv - initial shape (214114, 79)
  columns with missing values (top 10):
Flow Bytes/s    15
dtype: int64
Processing missing values for Friday-WorkingHours-Morning.pcap_ISCX.csv - initial shape (184145, 79)
  columns with missing values (top 10):
Flow Bytes/s    28
dtype: int64
Processing missing values for Monday-WorkingHours.pcap_ISCX.csv - initial shape (502983, 79)
  columns with missing values (top 10):
Flow Bytes/s    56
dtype: int64
Processing missing values for Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv - initial shape (252972, 79)
  columns with missing values (top 10):
Flow Bytes/s    15
dtype: int64
Processing missing values for Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv - initial shape (164300, 79)
  columns with missing values (top 10):
Flow Bytes/s    19
dtype: int64
Processing missing values for Tuesday-WorkingHours.pcap_ISCX.csv - initial shape (421844, 79)
  columns with missing values (top 10):
Flow Bytes/s    161
dtype: int64
Processing missing values for Wednesday-workingHours.pcap_ISCX.csv - initial shape (610794, 79)
  columns with missing values (top 10):
Flow Bytes/s    61
dtype: int64

In [24]:
# 3) Convert data types (numeric, categorical, datetime)
import dateutil

def try_parse_datetime(s):
    try:
        return pd.to_datetime(s, errors='coerce', utc=True)
    except Exception:
        return pd.NaT

for name, df in list(cleaned_dfs.items()):
    print('Converting types for', name)
    # datetime columns detection
    for col in df.columns:
        if 'time' in col.lower() or 'date' in col.lower() or 'ts' == col.lower():
            df[col] = try_parse_datetime(df[col])
    # numeric conversion for obvious numeric columns
    for col in df.columns:
        if any(k in col.lower() for k in ['size','bytes','length','count','port','ttl','duration']):
            df[col] = pd.to_numeric(df[col], errors='coerce')
    cleaned_dfs[name] = df
    print('  after conversion shape', df.shape)

'done'

Converting types for Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
  after conversion shape (223112, 79)
Converting types for Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
  after conversion shape (214114, 79)
Converting types for Friday-WorkingHours-Morning.pcap_ISCX.csv
  after conversion shape (184145, 79)
Converting types for Monday-WorkingHours.pcap_ISCX.csv
  after conversion shape (502983, 79)
Converting types for Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
  after conversion shape (252972, 79)
Converting types for Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
  after conversion shape (164300, 79)
Converting types for Tuesday-WorkingHours.pcap_ISCX.csv
  after conversion shape (421844, 79)
Converting types for Wednesday-workingHours.pcap_ISCX.csv
  after conversion shape (610794, 79)

'done'

In [25]:
# 4) Filter out irrelevant traffic (broadcasts, empties) and normalize
for name, df in list(cleaned_dfs.items()):
    print('Filtering', name, 'shape before', df.shape)
    # drop rows with zero packet size if column exists
    for sz_col in [c for c in df.columns if 'size' in c.lower() or 'bytes' in c.lower() or 'length' in c.lower()]:
        before = len(df)
        df = df[~(df[sz_col].fillna(0) == 0)]
        after = len(df)
        if before-after > 0:
            print(f'  removed {before-after} rows with zero {sz_col}')
    # drop local broadcast or multicast IPs if detectable
    for ip_col in [c for c in df.columns if 'ip' in c.lower() or 'addr' in c.lower()]:
        before = len(df)
        # simple heuristic: drop 255.255.255.255 and 0.0.0.0
        df = df[~df[ip_col].isin(['255.255.255.255','0.0.0.0'])]
        after = len(df)
        if before-after > 0:
            print(f'  removed {before-after} rows with broadcast in {ip_col}')
    # normalize protocol names to lower case
    for proto_col in [c for c in df.columns if 'proto' in c.lower() or 'protocol' in c.lower()]:
        df[proto_col] = df[proto_col].astype(str).str.lower()
    cleaned_dfs[name] = df.reset_index(drop=True)
    print('  after filtering shape', cleaned_dfs[name].shape)

'filtered'

Filtering Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv shape before (223112, 79)
  removed 5255 rows with zero Total Length of Fwd Packets
  removed 53859 rows with zero  Total Length of Bwd Packets
  removed 110325 rows with zero  Fwd Packet Length Min
  removed 50996 rows with zero  Fwd Packet Length Std
  removed 122 rows with zero  Bwd Packet Length Min
  removed 1494 rows with zero  Bwd Packet Length Std
  removed 1061 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv shape before (214114, 79)
  removed 56744 rows with zero Total Length of Fwd Packets
  removed 14629 rows with zero  Total Length of Bwd Packets
  removed 28780 rows with zero  Fwd Packet Length Min
  removed 108233 rows with zero  Fwd Packet Length Std
  removed 116 rows with zero  Bwd Packet Length Min
  removed 2874 rows with zero  Bwd Packet Length Std
  removed 2738 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Friday-WorkingHours-Morning.pcap_ISCX.csv shape before (184145, 79)
  removed 16909 rows with zero Total Length of Fwd Packets
  removed 19070 rows with zero  Total Length of Bwd Packets
  removed 41455 rows with zero  Fwd Packet Length Min
  removed 97885 rows with zero  Fwd Packet Length Std
  removed 226 rows with zero  Bwd Packet Length Min
  removed 3823 rows with zero  Bwd Packet Length Std
  removed 4777 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Monday-WorkingHours.pcap_ISCX.csv shape before (502983, 79)
  removed 60611 rows with zero Total Length of Fwd Packets
  removed 63463 rows with zero  Total Length of Bwd Packets
  removed 131247 rows with zero  Fwd Packet Length Min
  removed 228384 rows with zero  Fwd Packet Length Std
  removed 439 rows with zero  Bwd Packet Length Min
  removed 6622 rows with zero  Bwd Packet Length Std
  removed 12217 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv shape before (252972, 79)
  removed 23679 rows with zero Total Length of Fwd Packets
  removed 28938 rows with zero  Total Length of Bwd Packets
  removed 51625 rows with zero  Fwd Packet Length Min
  removed 139762 rows with zero  Fwd Packet Length Std
  removed 127 rows with zero  Bwd Packet Length Min
  removed 4457 rows with zero  Bwd Packet Length Std
  removed 4384 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv shape before (164300, 79)
  removed 18096 rows with zero Total Length of Fwd Packets
  removed 16944 rows with zero  Total Length of Bwd Packets
  removed 37160 rows with zero  Fwd Packet Length Min
  removed 85595 rows with zero  Fwd Packet Length Std
  removed 81 rows with zero  Bwd Packet Length Min
  removed 3128 rows with zero  Bwd Packet Length Std
  removed 3296 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Tuesday-WorkingHours.pcap_ISCX.csv shape before (421844, 79)
  removed 99298 rows with zero Total Length of Fwd Packets
  removed 29739 rows with zero  Total Length of Bwd Packets
  removed 104135 rows with zero  Fwd Packet Length Min
  removed 179481 rows with zero  Fwd Packet Length Std
  removed 27 rows with zero  Bwd Packet Length Min
  removed 57 rows with zero  Bwd Packet Length Std
  removed 9107 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)
Filtering Wednesday-workingHours.pcap_ISCX.csv shape before (610794, 79)
  removed 57738 rows with zero Total Length of Fwd Packets
  removed 59416 rows with zero  Total Length of Bwd Packets
  removed 267823 rows with zero  Fwd Packet Length Min
  removed 205852 rows with zero  Fwd Packet Length Std
  removed 396 rows with zero  Bwd Packet Length Min
  removed 10029 rows with zero  Bwd Packet Length Std
  removed 9540 rows with zero Fwd Avg Bytes/Bulk
  after filtering shape (0, 79)

'filtered'

In [ ]:
# Normalize IPs, ports, and protocol formats for consistency
# 4b) Normalize IPs, ports, and protocol formats for consistency
import re
from ipaddress import ip_address, IPv4Address, IPv6Address

def normalize_ip(x):
    if pd.isna(x):
        return x
    s = str(x).strip()
    # remove surrounding brackets for IPv6 [::1]:80 -> ::1:80
    s = s.strip('[]')
    # if ip:port, split off port
    if ':' in s and s.count(':') == 1 and re.match(r'^[0-9]+$', s.split(':')[-1]):
        s = s.split(':')[0]
    # for IPv6 with port like '::1:80' we cannot reliably split, so try ip_address validation
    try:
        # this will succeed for plain IPs
        ip_address(s)
        return s
    except Exception:
        # fallback: try to extract first token that looks like an IP
        tokens = re.split('[,;\/]+', s)
        for t in tokens:
            try:
                ip_address(t)
                return t
            except Exception:
                continue
        return np.nan

def normalize_port(x):
    if pd.isna(x):
        return x
    try:
        s = str(x).strip()
        # sometimes ports come as '80/HTTP' or '80.0'
        s = re.split('[^0-9]', s)[0]
        p = int(s)
        if 0 <= p <= 65535:
            return p
        return np.nan
    except Exception:
        return np.nan

def normalize_proto(x):
    if pd.isna(x):
        return x
    s = str(x).strip().lower()
    # common replacements
    s = s.replace('ip','ip').replace('tcp','tcp').replace('udp','udp')
    # if numeric proto (e.g., '6' for TCP), keep as string of number
    if s.isdigit():
        return s
    return s

# apply normalization heuristics to detected columns
for name, df in list(cleaned_dfs.items()):
    print('Normalizing formats for', name)
    # IP-like columns
    for col in [c for c in df.columns if 'ip' in c.lower() or 'addr' in c.lower()]:
        before = df[col].nunique(dropna=True) if col in df.columns else 0
        df[col] = df[col].apply(normalize_ip) if col in df.columns else df.get(col)
        after = df[col].nunique(dropna=True) if col in df.columns else 0
        print(f'  {col}: uniques before={before} after={after}')
    # Port-like columns
    for col in [c for c in df.columns if 'port' in c.lower()]:
        df[col] = df[col].apply(normalize_port) if col in df.columns else df.get(col)
        print(f'  normalized ports in {col} (non-numeric -> NaN)')
    # Protocol columns
    for col in [c for c in df.columns if 'proto' in c.lower() or 'protocol' in c.lower()]:
        df[col] = df[col].apply(normalize_proto) if col in df.columns else df.get(col)
        print(f'  normalized protocol values in {col} (sample=', df[col].dropna().unique()[:5], ')')
    cleaned_dfs[name] = df

'normalized'

In [26]:
# 5) Remove outliers in numeric columns conservatively
for name, df in list(cleaned_dfs.items()):
    print('Outlier removal for', name)
    for col in df.select_dtypes(include=[np.number]).columns:
        # skip small integer id-like columns by name heuristics
        if any(k in col.lower() for k in ['id','index','num']) and df[col].nunique() > 1000:
            continue
        # use IQR method
        series = df[col].dropna()
        if len(series) < 10:
            continue
        q1 = series.quantile(0.25)
        q3 = series.quantile(0.75)
        iqr = q3 - q1
        lower = q1 - 3 * iqr
        upper = q3 + 3 * iqr
        before = len(df)
        df = df[(df[col].isna()) | ((df[col] >= lower) & (df[col] <= upper))]
        after = len(df)
        if before-after > 0:
            print(f'  removed {before-after} rows as outliers from {col}')
    cleaned_dfs[name] = df.reset_index(drop=True)

'outliers removed'

Outlier removal for Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv
Outlier removal for Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv
Outlier removal for Friday-WorkingHours-Morning.pcap_ISCX.csv
Outlier removal for Monday-WorkingHours.pcap_ISCX.csv
Outlier removal for Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv
Outlier removal for Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv
Outlier removal for Tuesday-WorkingHours.pcap_ISCX.csv
Outlier removal for Wednesday-workingHours.pcap_ISCX.csv

'outliers removed'

In [ ]:
# 6) Aggregate flows by common keys (conservative - create aggregated copies)
aggregated_dfs = {}
for name, df in cleaned_dfs.items():
    # choose grouping keys if available
    keys = []
    for k in ['Source IP','SourceIP','src_ip','src','source','saddr']:
        if k in df.columns:
            keys.append(k)
            break
    for k in ['Destination IP','DestinationIP','dst_ip','dst','destination','daddr']:
        if k in df.columns:
            keys.append(k)
            break
    for k in ['protocol','proto','Protocol']:
        if k in df.columns:
            keys.append(k)
            break
    if len(keys) >= 2:
        # aggregate numeric columns by sum/mean where appropriate
        agg_num = {c: 'sum' for c in df.select_dtypes(include=[np.number]).columns}
        try:
            agg_df = df.groupby(keys, dropna=False).agg(agg_num).reset_index()
            aggregated_dfs[name] = agg_df
            print(f'  aggregated {name} -> {agg_df.shape} using keys {keys}')
        except Exception as e:
            print('  aggregation failed for', name, e)
    else:
        print('  not enough keys to aggregate for', name, 'keeping original')
        aggregated_dfs[name] = df.copy()

'aggregated'

In [ ]:
# 7) Drop columns that leak labels or are not useful for prediction
# Conservative default list - will drop columns commonly used as unique IDs or file-specific meta
drop_like = ['Flow ID','id','Id','index','timestamp_ms','frame_number']
clean_for_model = {}
for name, df in aggregated_dfs.items():
    to_drop = [c for c in df.columns if any(d.lower() == c.lower() for d in drop_like)]
    if to_drop:
        print(f'{name}: dropping columns {to_drop}')
    model_df = df.drop(columns=to_drop, errors='ignore').copy()
    clean_for_model[name] = model_df.reset_index(drop=True)

'dropped'

In [ ]:
# 8) Encode categorical variables (protocols, flags) into numeric form
from sklearn.preprocessing import LabelEncoder
encoded_for_model = {}
label_encoders = {}
for name, df in clean_for_model.items():
    df2 = df.copy()
    for col in df2.select_dtypes(include=['object', 'category']).columns:
        if df2[col].nunique() <= 200:
            le = LabelEncoder()
            try:
                df2[col] = le.fit_transform(df2[col].astype(str))
                label_encoders[(name, col)] = le
            except Exception as e:
                print('  encoding failed for', name, col, e)
    encoded_for_model[name] = df2

'encoded'

In [ ]:
# 9) Scale numeric features using RobustScaler (handles outliers better)
from sklearn.preprocessing import RobustScaler
scaled_for_model = {}
scalers = {}
for name, df in encoded_for_model.items():
    df3 = df.copy()
    num_cols = df3.select_dtypes(include=[np.number]).columns.tolist()
    if num_cols:
        # Prepare numeric matrix; fill NA for transformer but check for available samples
        X = df3[num_cols].fillna(0)
        # If there are zero rows or all values are NaN (after fillna -> check original), skip scaling
        if X.shape[0] == 0 or df3[num_cols].dropna(how='all').shape[0] == 0:
            print(f"Skipping scaling for {name}: no numeric samples available (shape={X.shape})")
            scalers[name] = None
        else:
            try:
                scaler = RobustScaler()
                df3[num_cols] = scaler.fit_transform(X)
                scalers[name] = (scaler, num_cols)
            except Exception as e:
                print(f"Scaling failed for {name}: {e}")
                scalers[name] = None
    else:
        print(f"No numeric columns to scale for {name}")
        scalers[name] = None
    scaled_for_model[name] = df3

"scaled"

In [ ]:
# 10) Validate logical consistency and basic labeling/balancing
from collections import Counter
labeled = {}
for name, df in scaled_for_model.items():
    print('Validating', name)
    # basic checks: no negative durations
    for col in df.select_dtypes(include=[np.number]).columns:
        if any('duration' in c.lower() for c in [col]):
            neg = (df[col] < 0).sum()
            if neg>0:
                print(f'  found {neg} negative values in {col}, setting to abs()')
                df[col] = df[col].abs()
    # labeling: if 'Label' or 'label' or 'attack' in columns, normalize to binary malicious/benign
    label_col = None
    for c in df.columns:
        if c.lower() in ['label','labels','attack','class']:
            label_col = c
            break
    if label_col is not None:
        # create binary label: 1 for malicious-like strings
        vals = df[label_col].astype(str).str.lower()
        malicious = vals.str.contains('attack|malicious|ddos|portscan|infiltr|webatt')
        df['__label__'] = malicious.astype(int)
        print('  label distribution:', Counter(df['__label__']))
        labeled[name] = df
    else:
        labeled[name] = df

'validated'

In [ ]:
# Remove noise and incomplete sessions (helps model learn valid patterns)

In [ ]:
# Ensure balanced class distribution (avoid bias toward majority class)

In [ ]:
# *Label data clearly as malicious or benign based on trusted criteria

In [ ]:
# 11) Save cleaned DataFrames to OUTPUT_DIR and print old vs new shapes/headers
# Ensure OUTPUT_DIR exists
try:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
except Exception as e:
    raise RuntimeError(f"Failed to create OUTPUT_DIR {OUTPUT_DIR}: {e}")

to_save = {}
# prioritize labeled -> scaled datasets if present
source_map = labeled if labeled else scaled_for_model
for name, df in source_map.items():
    out_name = name.replace('.csv', '_cleaned.csv')
    out_path = OUTPUT_DIR / out_name
    try:
        # For safety, write with index=False
        df.to_csv(out_path, index=False)
        to_save[name] = {'path': str(out_path), 'shape': df.shape, 'columns': list(df.columns)[:20]}
        print(f'Saved {out_path.name}: shape={df.shape}')
    except Exception as e:
        print(f'Failed to save {out_path}: {e}')

# print comparison with raw files when possible
for orig_name, info in to_save.items():
    raw_shape = raw_dfs.get(orig_name).shape if orig_name in raw_dfs else None
    print(orig_name, ' raw_shape=', raw_shape, ' cleaned_shape=', info['shape'])

"saved"